### ISSUE TITLE
edgeboard issues!

### ISSUE THREAD

**Issue by Xyj2020** [kopischke/fish.nova#2]
我将自己训练的非融合模型部署到FZ9A百度大脑开发板上，按照案例要求修改配置文件，运行时却报错“model open failed!"，这是怎么回事呢？急急急

**Comment by kopischke** [comment]
Um, are you sure you have the right repo? This is the repository of the [_fish_ shell](https://fishshell.com) syntax extension for the [_Nova_ editor](https://nova.app), and, as you can see, no code has been pushed to it yet, so you cannot actually have encountered an error with it.
